### ISSUE TITLE
Is this drop in compatible with the DigitalOcean version?

### ISSUE THREAD

**Issue by willfurnell** [sol1/icingaweb2-module-netbox#25]
Hello,
We currently have a _lot_ of import rules etc. configured with the https://github.com/digitalocean/icingaweb2-module-netboximport DigitalOcean version of this import source. I'm sorry but I'm not 100% clear - can I use this source as a drop in replacement to that one or is there a more involved migration process?
Thanks!

**Comment by davekempe** [comment]
Hey @willfurnell thanks for checking this out. We have long departed from that codebase, and this is kinda a complete rewrite and then a large change from the digitalocean version. We would be happy to assist with any errors you come across or problems, however I suspect a lot of the fields would be different. We have added so many features it would be worth it I reckon. Most of the things would come across, but it is not a drop in replacement.
If I was going to attempt this, I would switch 1 or 2 of the sources over, and see how you go, and then figure out what broke. You can then perhaps script a complete dump of the director baskets, then with some aggressive sedding and find replace or something you could convert the old rules into the new ones. The director baskets are just json, so you can safely manipulate them and then restore them.

**Comment by sol1-matt** [comment]
Hi @willfurnell,

It isn't a drop in replacement but I suspect you may be able to get the import sources to output datasets that are very close. 

Since the modules use a different namespace you should have no problem having both of them installed and so you can test it out without affecting your current configuration by cloning your current import sources and changing the cloned import source config.

Like you we've had to deal with a lot of import rules with various configurations, where possible we've tried to automate the manipulation of data inside the import module to create new fields so we don't need to add rules, or deal with flatten data that will never get used. You can find documentation on these [convenience fields in the README](https://github.com/sol1/icingaweb2-module-netbox#convenience-fields-for-common-modifiers). There are also options to link services, contacts and IP Ranges info to devices and virtual machines.

**Comment by willfurnell** [comment]
Thank you both - it was pretty easy to migrate over to using this with some only minor changes in the import source config!
