### ISSUE TITLE
Custom field data type

### ISSUE THREAD

**Issue by Azmodeszer** [sol1/icingaweb2-module-netbox#47]
In the [Best Practices](https://github.com/sol1/icingaweb2-module-netbox?tab=readme-ov-file#best-practices) section, it's explicitly stated to use the `Selection` type for the custom field that defines whether an object is part of the monitoring, but I'm wondering why exactly a simple boolean field wouldn't suffice? Are the import sources tailored around a text value in particular? Just curious if that's just a suggestion or not, thanks.

**Comment by sol1-matt** [comment]
The reason for a custom field that is `Selection` is based on a couple of different things which I've found are best solved with a `Selection`.

**Why custom field over something else like tag or role?**
- Because a custom field for monitoring import makes it easy for humans to look at something in Netbox and figure out if it should be monitored or not with out doing the math of, if it has a role of 'foo' or a tag of 'bar' it is monitored.
- If humans have the option to have overlapping groups, eg: role=foo and tag=bar, then one of those humans will select both. In your automation imports the same object into 2 different sets Import Sources will result in 2 different sync rules writing to the same object, likely 2 different config values. The end result is 1000's of changes in the activity log and monitoring that flicks back between working and not working. _not fun in my personal experience :)_

**Why a `Selection` over a `Boolean`?**
- Because if you end up with lots of hosts being imported you may want to break them up into groups so 
  - updates are smaller (per group)
  - mistakes in automation have a smaller impact
- Because if you need to create different host objects it is neater to use separate import source / sync rule combinations over a single import source / sync rule combination that has a lot of sync rule filters

On that last point I'll give you an example.

You want to monitor VMWare hosts running linux and RDS instances in AWS. 

The linux hosts you choose to setup with agents so you can monitor things on them, there are a bunch of rules agents will need along with the regular stuff like address, etc....

The RDS instances though you don't directly do anything with them, all monitoring is via AWS itself, so it's host object is radically different from the linux host above and needs things like the AWS specific values. 

If you have a single set of sync rule properties for both of these you will likely end up with almost as many sync rule properties as if you split it up and had 2 sync rules with their own properties. But that single set of properties will be full of filters which make trying to figure out problems much harder. 

**Consistency**
I use `Selection` and recommend it as a best practice as I'm responsible for the setup of and top level support of half a dozen Icinga/Netbox integrations and even if a integration never will need anything other than `Monitor (Default)` and `Do not Monitor` it is easier if everybody is using the same mechanism, there is no "How does this one work" when a new person has to support a given customer or ours. This consistency also helps us as a community when figuring stuff out.

The above all said you could use a boolean if that suits your setup.

**Comment by Azmodeszer** [comment]
Gotcha. Thanks for the detailed response!
